services:
  server_1:
    container_name: server_1
    image: server_1
    build:
      context: .
    environment:
      - 'APP_TYPE=server'
      - 'REDIS_URL=redis://valkey:6379'
    depends_on:
      valkey:
        condition: service_started
    restart: on-failure
    ports:
      - "3000:3000"
    expose:
      - 3000

  worker_1:
    container_name: worker_1
    image: worker_1
    build:
      context: .
    environment:
      - 'APP_TYPE=worker'
      - 'REDIS_URL=redis://valkey:'
    depends_on:
      valkey:
        condition: service_started
    restart: on-failure

  worker_2:
    container_name: worker_2
    image: worker_2
    build:
      context: .
    environment:
      - 'APP_TYPE=worker'
      - 'REDIS_URL=redis://valkey:'
    depends_on:
      valkey:
        condition: service_started
    restart: on-failure

  worker_3:
    container_name: worker_3
    image: worker_3
    build:
      context: .
    environment:
      - 'APP_TYPE=worker'
      - 'REDIS_URL=redis://valkey:'
    depends_on:
      valkey:
        condition: service_started
    restart: on-failure

  valkey:
    container_name: 'queue-redis'
    image: 'valkey/valkey:7.2.5'
    ports:
      - '6379:6379'